### ISSUE TITLE
The latest v0.6 breaks the SM for me

### ISSUE THREAD

**Issue by Arin-426** [rounk-ctrl/TranslucentSM#16]
Upon running the latest version of start.exe, the Start Menu wouldn't open. And the StartMenuExperience stops responding. I tested again with v0.5, and it works as usual. I am on Windows 10 (22H2).

**Comment by Arin-426** [comment]
Also, how can I make it run automatically every time I boot/logon? I tried Task Scheduler, but for some reason, the task isn't executing automatically, it runs manually just fine, but doesn't execute automatically. What am I missing? Can anyone export their task and share it with me?

**Comment by rounk-ctrl** [comment]
huh, can you try this version ?
[start.zip](https://github.com/rounk-ctrl/TranslucentSM/files/14887138/start.zip)

**Comment by Arin-426** [comment]
> huh, can you try this version ? [start.zip](https://github.com/rounk-ctrl/TranslucentSM/files/14887138/start.zip)

Same behavior. Start menu doesn't open and-
![image](https://github.com/rounk-ctrl/TranslucentSM/assets/98632017/cbfab100-b3a4-4351-acb3-b1f29e319860)

By the way, I am also using Translucent TB, DWMBlur Glass and Translucent Flyout if that matters.
