### ISSUE TITLE
Doesn't Work?

### ISSUE THREAD

**Issue by darklordcoz** [rounk-ctrl/TranslucentSM#17]
I'm on Windows 11 23H2 and use Start All Back and Translucent TB. When I click on start.exe nothing happens. Maybe I don't understand how to install it? Any help would be greatly appreciated.

**Comment by rounk-ctrl** [comment]
nothing appears on the start menu?

**Comment by rounk-ctrl** [comment]
oh you use startallback. It only works with the default windows 10/11 start menu

**Comment by Apis035** [comment]
Just found this today and had similar issue. Using Windows 10 22H2, no other taskbar modifying app. With version 0.6 start menu does not appear at all while version 0.5 works fine.

**Comment by rounk-ctrl** [comment]
yeaa its fixed for windows 10
