### ISSUE TITLE
I have two problems with TranslucentSM

### ISSUE THREAD

**Issue by Dhyfer1** [rounk-ctrl/TranslucentSM#2]
Hi @rounk-ctrl 

Thank you for creating TranslucentSM, it's very cool, it's similar to [BeautySearch](https://github.com/krlvm/BeautySearch) for Win10

I have placed the executable inside the start menu folder `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup` to run every time I start Windows. Then, the first time TranslucentSM is run, it creates a dll file (TAPdll.dll) in the same path where the executable is, and every time Windows is run, the following box always appears:

![image_2](https://github.com/rounk-ctrl/TranslucentSM/assets/50301201/de818779-2eb6-4534-8396-e005875435cd)

and if I delete the dll file, it is only recreated when start.exe is run after Windows startup/restart and the same box you already saw appears again.

Another thing, the translucent effect is lost when I click on the search field of the start menu as you can see in the video, can you fix it?

https://github.com/rounk-ctrl/TranslucentSM/assets/50301201/fb5a811c-ad29-4737-8481-ca3a534543cb

**Comment by rounk-ctrl** [comment]
You can try using Task Scheduler to run the app ig

**Comment by Dhyfer1** [comment]
> You can try using Task Scheduler to run the app ig

Thank you very much, your workaround worked. I just had to create a basic task in Task Manager and the popup window that I have shown you has not reappeared, but it is still pending that you can solve the bug that I have pointed out in the video, where the translucent effect is lost when I click on the search bar of the start menu.

**Comment by rounk-ctrl** [comment]
that would require injecting into search, which is currently not possible since idk how to un-inject the dll from start

**Comment by Dhyfer1** [comment]
> that would require injecting into search, which is currently not possible since idk how to un-inject the dll from start

It's okay, no problem. I'll have to make do with what's there. Thank you anyway.

**Comment by Dhyfer1** [comment]
> that would require injecting into search, which is currently not possible since idk how to un-inject the dll from start

It's okay, no problem. I'll have to make do with what's there. Thank you anyway.
