### ISSUE TITLE
TranslucentSM doesn't re-inject itself when Explorer.exe is restart and has to be run again

### ISSUE THREAD

**Issue by Skyyblaze** [rounk-ctrl/TranslucentSM#22]
I noticed that when explorer.exe gets restarted TranslucentSM isn't hooking the Start Menu anymore and I have to rerun the program. It would be nice if TranslucentSM could automatically re-inject itself.

**Comment by rounk-ctrl** [comment]
tracked in the other issue

**Comment by Skyyblaze** [comment]
I see, I missed that sorry.
