### ISSUE TITLE
Every version after the 0.5 doesnt work on windows 11

### ISSUE THREAD

**Issue by ghost** [rounk-ctrl/TranslucentSM#35]
i tried every version provided after the 0.5 version and none of them work... on my windows 11 pc.

i am ok with using 0.5 but i think you should get it fixed...

when i run a version above 0.5 it runs some terminal window and dissapears. after that window appears i cant open the start menu for like 5 seconds and after 5 seconds the start menu is normal with no translucent background...

**Comment by Alienmoon** [comment]
> i tried every version provided after the 0.5 version and none of them work... on my windows 11 pc.
> 
> i am ok with using 0.5 but i think you should get it fixed...
> 
> when i run a version above 0.5 it runs some terminal window and dissapears. after that window appears i cant open the start menu for like 5 seconds and after 5 seconds the start menu is normal with no translucent background...

Thanks for the info, Downgraded and this now works on Windows 11, thanks again.
