### ISSUE TITLE
reapply on explorer reload

### ISSUE THREAD

**Issue by oatmealcookiec** [rounk-ctrl/TranslucentSM#4]
Great utility, work on Windows 11 23h2.
But there is a small problem - after restarting explorer.exe need  restart start.exe
Is it possible to fix it somehow and keep the program constantly?

**Comment by bbmaster123** [comment]
that is something that could be added in down the road, but for now there are a few good workarounds.
I'd suggest to create a task in Task Scheduler, have it trigger when explorer.exe starts, and point it to start.exe, this should have the effect of automatically restarting TranslucentSM along with explorer
cheers

**Comment by oatmealcookiec** [comment]
Thanks for the quick response.
Will be waiting for an update!

**Comment by oatmealcookiec** [comment]
> it happens because after restarting explorer, StartMenuExperienceHost.exe also gets restarted

this is understandable, but there is 100% a way for it to work even after restarting explorer, as the author of the program wrote

**Comment by rounk-ctrl** [comment]
._. i am the author. Sure there is a way, but that would require the app constantly running in the background

**Comment by oatmealcookiec** [comment]
> ._. i am the author. Sure there is a way, but that would require the app constantly running in the background

Oh, sorry. I didn't notice that you are the author.
Is it possible to make a .dll library that can be registered using the regsvr32?
Well, or at least a version that will work constantly in the background?
With respect.

**Comment by rounk-ctrl** [comment]
yea i plan to make it a regsvr32 dll

**Comment by oatmealcookiec** [comment]
> yea i plan to make it a regsvr32 dll

Great news. Waiting for update. Thank you

**Comment by bbmaster123** [comment]
haha yes I am just a guy who likes to help ;)
All credit to Rounk-ctrl!

If Rounk is making this into a registered dll, that will be a better solution than my above work-around, and I would probably suggest to just wait instead.

 That said, I have it auto-restarting now with v0.4 using a scheduled task that launches start.exe every time startmenuexperiencehost.exe is started, and the cmd window is hidden using advancedRun (also useful for other mods like TranslucentFlyouts v2

**Comment by oatmealcookiec** [comment]
Yes, I didn't look at who the author was at first :)
it would be ideal if the author also added the function of deleting (hiding) the 'recommend' section
I know about the scheduled task in the scheduler, but it's still better to wait until the author does it in the .dll regsvr32

**Comment by AlexanderJustin183** [comment]
use Explorer hook like ExplorerBlurMica?

**Comment by rounk-ctrl** [comment]
how will **explorer** hook help with start menu, which is hosted in a diff process

**Comment by AlexanderJustin183** [comment]
shellexperencehost.exe hook?

**Comment by Arin-426** [comment]
> haha yes I am just a guy who likes to help ;) All credit to Rounk-ctrl!
> 
> If Rounk is making this into a registered dll, that will be a better solution than my above work-around, and I would probably suggest to just wait instead.
> 
> That said, I have it auto-restarting now with v0.4 using a scheduled task that launches start.exe every time startmenuexperiencehost.exe is started, and the cmd window is hidden using advancedRun (also useful for other mods like TranslucentFlyouts v2 for example)

I tried making a task but it won't execute (on logon) but runs fine manually. Could you export and share your task?

**Comment by bbmaster123** [comment]
@Arin-426 Sorry for the delay, I sometimes don't see my messages on this account
Set the trigger to custom event filter, begin task on an event, and set the action to load a .bat file with the patch to start.exe
I have my .bat pointing to advancedrun.exe with arguments telling it to load a second .bat which contains the path to start.exe, which allows me to set the command prompt to hidden, so that it doesn't pop up on load.

let me know if you need more clarification or anything! :D 

#### run-sm.bat
```
cd %USERPROFILE%\documents\translucentSM\
start advancedrun /run /advancedrunSM.cfg
```
#### advancedrun.cfg
```
[General]
WinPos=2C 00 00 00 00 00 00 00 01 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 25 01 00 00 1B 01 00 00 5A 04 00 00 A3 03 00 00
EXEFilename=C:\Users\[name]\Documents\TranslucentSM\start.exe
CommandLine=
StartDirectory=C:\Users\[name]\Documents\TranslucentSM\
WaitProcess=0
PriorityClass=32
WindowState=0
UseWindowPosition=0
WindowPosition=20,20
UseWindowSize=0
WindowSize=640,400
RunAs=6
RunAsProcessName=
EnvironmentVariablesMode=1
OSCompatMode=0
UseSearchPath=0
ParseVarCommandLine=0
UseAffinityMask=0
AffinityMask=0 1
Compat640480=0
CompatDisableVisualThemes=0
CompatDisableDesktopComp=0
CompatDisableFullScreenOpt=0
CompatHighDPI=0
CompatColors=0
RunAsUserName=
RunAsDomain=
RunFromService=0
ComputerName=
RunMode=1
ShellExecuteAction=open
CommandWindowMode=1
[EnvironmentVariables]
Lines=0
```
#### Custom Event Filter
```
<QueryList>
  <Query Id="0" Path="Security">
    <Select Path="Security">
     *[System[Provider[@Name='Microsoft-Windows-Security-Auditing'] and Task = 13312 and (band(Keywords,9007199254740992)) and (EventID=4688)]] 
   and 
     *[EventData[Data[@Name='NewProcessName'] and (Data='C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\startmenuexperiencehost.exe')]]
    </Select>
  </Query>
</QueryList>
```

**Comment by Undisputed00x** [comment]
Why is this issue still open, another guy have already provided a workaround https://github.com/rounk-ctrl/TranslucentSM/issues/13#issuecomment-2023989762.
Make a logon scheduled task of that and you are fine to go.

**Comment by rounk-ctrl** [comment]
because i need to implement it?

**Comment by Kevin0ders0** [comment]
> @Arin-426 Sorry for the delay, I sometimes don't see my messages on this account Set the trigger to custom event filter, begin task on an event, and set the action to load a .bat file with the patch to start.exe I have my .bat pointing to advancedrun.exe with arguments telling it to load a second .bat which contains the path to start.exe, which allows me to set the command prompt to hidden, so that it doesn't pop up on load.
> 
> EDIT: Forgot the step where you need to turn on detailed tracking in group policy editor under Computer Configuration > Policies > Windows Settings > Security Settings > Advanced Audit Configuration > Detailed Tracking
> 
> let me know if you need more clarification or anything! :D
> 
> #### run-sm.bat
> ```
> cd %USERPROFILE%\documents\translucentSM\
> start advancedrun /run /advancedrunSM.cfg
> ```
> 
> #### advancedrun.cfg
> ```
> [General]
> WinPos=2C 00 00 00 00 00 00 00 01 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 25 01 00 00 1B 01 00 00 5A 04 00 00 A3 03 00 00
> EXEFilename=C:\Users\[name]\Documents\TranslucentSM\start.exe
> CommandLine=
> StartDirectory=C:\Users\[name]\Documents\TranslucentSM\
> WaitProcess=0
> PriorityClass=32
> WindowState=0
> UseWindowPosition=0
> WindowPosition=20,20
> UseWindowSize=0
> WindowSize=640,400
> RunAs=6
> RunAsProcessName=
> EnvironmentVariablesMode=1
> OSCompatMode=0
> UseSearchPath=0
> ParseVarCommandLine=0
> UseAffinityMask=0
> AffinityMask=0 1
> Compat640480=0
> CompatDisableVisualThemes=0
> CompatDisableDesktopComp=0
> CompatDisableFullScreenOpt=0
> CompatHighDPI=0
> CompatColors=0
> RunAsUserName=
> RunAsDomain=
> RunFromService=0
> ComputerName=
> RunMode=1
> ShellExecuteAction=open
> CommandWindowMode=1
> [EnvironmentVariables]
> Lines=0
> ```
> 
> #### Custom Event Filter
> ```
> <QueryList>
>   <Query Id="0" Path="Security">
>     <Select Path="Security">
>      *[System[Provider[@Name='Microsoft-Windows-Security-Auditing'] and Task = 13312 and (band(Keywords,9007199254740992)) and (EventID=4688)]] 
>    and 
>      *[EventData[Data[@Name='NewProcessName'] and (Data='C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\startmenuexperiencehost.exe')]]
>     </Select>
>   </Query>
> </QueryList>
> ```

Hey.. I did the same thing on my own... but it didn´t worked.. I´m searching for hours what I did wrong.. can u help me a bit? pls
